services:
  app:
    build: 
      context: ./celia-app # Path to the app
      dockerfile: Dockerfile-back
    container_name: nestjs_app
    working_dir: /usr/src/app
    volumes:
      - ./celia-app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    command: >
      sh -c "
      npm install &&
      npm run start:dev"
    depends_on:
      - db

  db:
    build:
      context: . # Path to the db
      dockerfile: Dockerfile-db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: celia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

volumes:
  postgres_data:
